import { NavBar } from '@/components/Navbar';
import { ThemeProvider } from '@/components/theme';
import { Toaster } from '@/components/ui/toast';
import { cn } from '@/lib/utils';
import { UserProvider } from '@/provider/UserProvider';
import { createClient } from '@/utils/supabase/server';
import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import { cookies } from 'next/headers';
import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const supabase = createClient(cookieStore);

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html
      suppressHydrationWarning
      lang="pt-br"
      className={cn('antialiased', 'font-sans', geist.variable)}
    >
      <body className={cn('h-screen')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider user={user}>
            <NavBar />
            <main className="h-[95%]">
              <Toaster />

              {children}
            </main>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
